---
bibliography: bibliografi.bib  
csl: chicago-author-date.csl
always_allow_html: true
---

# Hvorfor dette notatet? {.unnumbered}

Dette notatet oppsummerer ulike forelesningsnotater og undervisningsopplegg i anvendt kvantitativ analyse. Hensikten er å forsøke å formidle sentrale konsepter og teknikker, samt gi "oppskrift" på prosedyre i ulike verktøy. 

## Programvare {.unnumbered}

Notatet er skrevet med bruk av R [@rcoreteamLanguageEnvironmentStatistical2021] og RStudio [@rstudioteamRStudioIntegratedDevelopment2022]. R er en velkjent programvare innenfor statistikk, dataanalyse, datamodellering osv. R har noen store fordeler; det er gratis, det kjører på "alle" operativsystemer, og det har et svært stort bruker- og utviklermiljø som i all hovedsak deler alt gratis. Det er også enkelt å finne løsninger på det meste gjennom veiledninger og brukerforum på nett. Selve R er et programmeringsspråk og utviklermiljø for statistikk som gir en kjernefunksjonalitet innenfor datahåndtering, kalkulasjoner, dataanalyse, datamodellering, grafisk framstilling av data o.l. 

R kommer med 14 basis "pakker". Det store potensialet ligger imidlertid i at brukerne av R utvikler tilleggspakker som man bruker i R, det finnes pr. april 2022 over 19000 ulike pakker som bygger på kjernen i R. Alle pakkene tilbyr ulike tilrettelagte løsninger for ulike problemer/analyser. 

Den største ulempen med R er at brukergrensesnittet er veldig ulikt hva vi kjenner fra Microsoft Office-typen brukergrensesnitt, så det vil ta litt tid å bli kjent med programmet. I tillegg er brukergrensesnittet kodebasert og ikke menybasert, og kan (dessverre) virke avskrekkende. Likevel, det er et utrolig kraftig verktøy hvis man tar seg tid til å lære seg det grunnleggende.

Brukere av notatet vil sannsynligvis kjøre programvare som enten SPSS eller Stata. Konsepter og eksempler i notatet er som sagt laget og kjørt i R, men tilhørende videoer for framgangsmåte i SPSS og Stata for å få fram tilsvarende analyser på samme eksempler som i notatet ligger tilgjengelig. 

I tillegg er det på sin plass å nevne alternativer til store og dyre programvarepakker som SPSS og Stata som mer og mer framstår som reelle og gode alternativer. To av disse, [jamovi](https://www.jamovi.org/) og [JASP](https://jasp-stats.org/), har sterkt voksende bruk (også i akademia) rundt om i verden. Dette er grafisk tiltalende og funksjonsrike statistikkpakker som kjører med R i bakgrunnen (alle analyser i jamovi og JASP bruker R), og som også kan inkludere R kode direkte. Det gjør at man kan utnytte alle pakkene skrevet for R direkte i de grafiske brukergrensesnitt. I tillegg kan man (i varierende grad mellom de to) hente ut R-kode fra analyser man gjør gjennom det grafiske brukergrensesnittet - noe som kan gjøre en overgang/introduksjon til R lettere om man vil den veien. 

Leseren står selvsagt fritt til å hoppe elegant over alle verktøy som ikke er interessante. Det er klare fordeler og ulemper med alle, men forhåpentligvis vil de fleste finne et verktøy de kan bruke i utvalget vi har tatt med.

Der det er naturlig, som ved bruk av R og RStudio, er kodingen inkludert slik at eksempler skal kunne replikeres av leseren, men vi går ikke inn på R utover dette. Kodingen er gjengitt fortløpende der analysen er gjort. Vi har brukt R/RStudio og rmarkdown [@allaireRmarkdownDynamicDocuments2022] -- en såkalt pakke til R -- i produksjonen av dette notatet. R baserer seg som sagt på bruk av ulike "pakker" som er utviklet av forskjellige utviklere og som er fritt tilgjengelig. Mange av disse har også datasett inkludert slik at det er enkelt å replikere eksempler. Så langt det er mulig har vi basert oss på at det vi viser som eksempler skal være replikerbare for leseren. 

Vi har lite fokus på matematikk og formler i den forstand at vi ikke utleder i dybden forklaring på ulike formler. Vi tror det er fullt mulig å ha en praktisk forståelse og anvendt bruk av kvantitative analyser uten å ha dyptgående kjennskap til de matematiske eller statistiske forklaringene. Likevel, det er heller ikke slik at vi absolutt skal unngå dette. Vi har derfor inkludert noe bakgrunnskunnskap for å skape en
ramme rundt kjernen i notatet der vi tenker det kan være interessant for de som ønsker å fordype seg noe mer. 
